using RoslynCSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;

class GMLFighter : GMLObject
{

    private const string FIGHTER_PREFAB_PATH = "";

    private static GMLFighter fighterPrefab;

    /// <summary>
    /// Callback for the initialize script
    /// </summary>
    private Action<GMLSymbolTable> runInit;

    /// <summary>
    /// Callback for the update script
    /// </summary>
    private Action<GMLSymbolTable> runUpdate;

    static GMLFighter()
    {
        fighterPrefab = AssetDatabase.LoadAssetAtPath<GMLFighter>(FIGHTER_PREFAB_PATH);
    }

    public override void Awake()
    {
        base.Awake();
        //This will probably end up being auto-generated by archai, but will need to be compiled and run anyway.
        runInit.Invoke(instanceScope);
    }

    public override void Update()
    {
        base.Update();
        runUpdate.Invoke(instanceScope);
    }

    public void applyColors()
    {

    }

    public static GMLFighter createGMLFighter(GMLRoom room, Action<GMLSymbolTable> runInit, Action<GMLSymbolTable> runUpdate)
    {
        GMLFighter fighter = Instantiate(fighterPrefab, room.transform);
        fighter.runInit = runInit;
        return fighter;
    }
}
